# Generated by Django 5.2 on 2025-04-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Skill',
        ),
    ]
