# Generated by Django 5.2 on 2025-04-06 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_skills_project_rename_projects_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=15)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Academics',
            },
        ),
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_title', models.CharField(blank=True, max_length=120)),
                ('map', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='photos/')),
            ],
            options={
                'verbose_name_plural': 'Basics',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/blog/')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
