# Generated by Django 5.2 on 2025-04-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_academy_basics_blog_service_delete_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='github',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basics',
            name='linkedine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basics',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basics',
            name='twitter',
            field=models.TextField(blank=True),
        ),
    ]
