# Generated by Django 5.2 on 2025-04-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basics_github_basics_linkedine_basics_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
