# Generated by Django 5.2 on 2025-04-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Project',
        ),
    ]
