# Generated by Django 5.2 on 2025-04-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_service_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Course',
        ),
    ]
