# Generated by Django 5.2 on 2025-04-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_blog_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
    ]
