# Generated by Django 5.2 on 2025-04-18 20:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=30)),
                ('web_title', models.CharField(blank=True, max_length=120)),
                ('map', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='photos/')),
                ('phone', models.TextField(blank=True)),
                ('linkedine', models.TextField(blank=True)),
                ('github', models.TextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.DeleteModel(
            name='Basics',
        ),
        migrations.AlterField(
            model_name='academy',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/course/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=50),
        ),
    ]
