# Generated by Django 5.2 on 2025-05-07 16:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact_delete_basics_alter_academy_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
                ('pinterest', models.TextField(blank=True)),
                ('footer', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
