# Generated by Django 5.2 on 2025-05-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_basic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basic',
            options={'verbose_name_plural': 'Basics'},
        ),
    ]
