# Generated by Django 5.2 on 2025-05-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_basic_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='basic',
            name='pinterest',
        ),
    ]
