# Generated by Django 5.2 on 2025-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_basic_facebook_remove_basic_pinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='basic',
            name='github',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='basic',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
