# Generated by Django 5.2 on 2025-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_basic_email_basic_github_basic_phone_basic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='icon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
